### PR TITLE
fix(cli): Add option to bypass confirmation to download binaries

### LINKED ISSUE #1188: [Cli] add option to bypass confirmation in `setup`
```
Setup will start to download binaries:
- polkadot 	 Approx. size  119  MB
- polkadot-parachain 	 Approx. size  135  MB
Total approx. size:  254 MB

Do you want to continue? (y/n)
```

### PR DESCRIPTION
**Pull request by pepoviola**
fix #1188

### CODE REVIEW

File: javascript/packages/cli/src/actions/setup.ts [hunk 1]
```diff
@@ -12,9 +12,10 @@ const options: OptIf = {};
  * Setup - easily download latest artifacts and make them executable in order to use them with zombienet
  * Read more here: https://paritytech.github.io/zombienet/cli/setup.html
  * @param params binaries that willbe downloaded and set up. Possible values: `polkadot` `polkadot-parachain`
+ * @param opts Options from cli, currently only support `yes` to bypass the confirmation to download the binaries
  * @returns
  */
-export async function setup(params: any) {
+export async function setup(params: any, opts: any) {
```
Comment (wirednkod) [inline javascript/packages/cli/src/actions/setup.ts:18]:
```suggestion
export async function setup(params: any, opts?: any) {
```

File: javascript/packages/cli/src/actions/setup.ts [hunk 2]
```diff
@@ -87,15 +88,17 @@ export async function setup(params: any) {
...
-  const response = await askQuestion(
-    decorators.yellow("\nDo you want to continue? (y/n)"),
-  );
-  if (response.toLowerCase() !== "n" && response.toLowerCase() !== "y") {
-    console.log("Invalid input. Exiting...");
-    return;
-  }
-  if (response.toLowerCase() === "n") {
-    return;
+  if (!opts.yes) {
```
Comment (wirednkod) [inline javascript/packages/cli/src/actions/setup.ts:91]:
```suggestion
  if (!opts?.yes) {
```
