### PR TITLE
fix(orchestrator): set undying/adder collators not validators by default

### LINKED ISSUE #1245: Fix collator (undying/adder) cmd args
Followup from https://github.com/paritytech/polkadot/pull/7617#issuecomment-1678536346, we should not use `--validator` in those collators cmd.

### PR DESCRIPTION
**Pull request by pepoviola**
fix #1245. Don't set `undying/adder` collators as validators by default.

### CODE REVIEW

File: javascript/packages/orchestrator/src/configGenerator.ts [hunk 1]
```diff
@@ -529,11 +529,20 @@ async function getCollatorNodeFromConfig(
...
   const externalPorts = await getExternalPorts(provider, ports, collatorConfig);
 
+  // By default cumulus collators are `validators`, this implies that we will
+  // run those with this flag `--collator`.
+  const isValidator =
+    collatorConfig.validator !== undefined
+      ? collatorConfig.validator
+      : cumulusBased
+      ? true
+      : false;
```
Comment (mrcnski) [inline javascript/packages/orchestrator/src/configGenerator.ts:539]: I'm having a hard time parsing this nested ternary statement. Also, I think JS has a `??` operator or something similar you could use, IIRC.

File: javascript/packages/orchestrator/src/cmdGenerator.ts [hunk 2]
```diff
@@ -270,7 +270,7 @@ export async function genCmd(
     const parachainIdArgIndex = args.findIndex((arg) =>
       arg.includes("--parachain-id"),
     );
-    args.splice(parachainIdArgIndex, 1);
+    if( parachainIdArgIndex >=0) args.splice(parachainIdArgIndex, 1);
```
Comment (wirednkod) [inline javascript/packages/orchestrator/src/cmdGenerator.ts:273]:
```suggestion
    if( parachainIdArgIndex >=0 ) args.splice(parachainIdArgIndex, 1);
```

File: javascript/packages/orchestrator/src/configGenerator.ts (hunk 1 above)
Comment (wirednkod) [reply javascript/packages/orchestrator/src/configGenerator.ts:539]: Correct. I think this could simplier be:
```suggestion
  const isValidator = !!collatorConfig.validator || !!cumulusBased;
```

Comment (pepoviola) [reply javascript/packages/orchestrator/src/configGenerator.ts:539]: Sounds good to me, old ternary addiction 😂

we can also use 
```
const isValidator = Boolean(collatorConfig.validator) || Boolean(cumulusBased);
```

Thanks!!

File: javascript/packages/orchestrator/src/cmdGenerator.ts (hunk 2 above)
Comment (pepoviola) [reply javascript/packages/orchestrator/src/cmdGenerator.ts:273]: Is this something that the `linting` should `fix` or at least catch?

Comment (pepoviola) [reply javascript/packages/orchestrator/src/cmdGenerator.ts]: fixed by linter.

File: javascript/packages/orchestrator/src/configGenerator.ts (hunk 1 above)
Comment (pepoviola) [reply javascript/packages/orchestrator/src/configGenerator.ts:540]: I just add a better comment about this ternary, resolving here.
Thx!

**Review by wirednkod — APPROVED** [review]
