### PR TITLE
Alter logging to support `silent` in moonbeam decorator

### LINKED ISSUE #885: Make console output mutable in Moonbeam decorator
### Issue Description

As part of the Moonbeam decorator, we add some console logging for the genesis authority. Whilst this can be useful, can we add an option to mute this by default, or move the level to debug/trace?

https://github.com/paritytech/zombienet/blob/c535f7d06c6b50a939c4c6aeada6b4a5f07cb4fc/javascript/packages/orchestrator/src/paras-decorators/moonbeam.ts#L45

### Steps to reproduce the issue

Steps to reproduce the issue
1. run a zombie network via orchestrator, for a minimal moonbeam setup
  a. `await zombie.start("", path, { silent: true });` 
2. Regard the console output

### Describe the results you received

Something along the lines of this gets printed:
```
        👤 Added Genesis Authority alith - 5HEL3iLyDyaqmfibHXAXVzyQq4fBqLCHGMEYxZXgRAuhEKXX
[Object: null prototype] {
  mappings: [
    [
      '5HEL3iLyDyaqmfibHXAXVzyQq4fBqLCHGMEYxZXgRAuhEKXX',
      '0xf24FF3a9CF04c71Dbc94D0b566f7A27B94566cac'
    ]
  ]
}
```

### Describe the results you expected

No output unless otherwise requested. There is no other network information printed to console, this shouldn't be any different.

### Zombienet version

"@zombienet/orchestrator": "^0.0.34"

### Provider

Native

### Provider version

```yaml
polkadot 0.9.40-a2b62fb872b
moonbeam 0.30.0-3bb936c32e1
```

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Adds noise to logs but not a functional issue

### Screenshots

image

### PR DESCRIPTION
**Pull request by wirednkod**
Fixes #885

### CODE REVIEW

**Review by pepoviola — APPROVED** [review]

File: javascript/packages/orchestrator/src/paras-decorators/moonbeam.ts [hunk 1]
```diff
@@ -52,13 +52,20 @@ async function addAuthority(specPath: string, node: Node, key: GenesisNodeKey) {
...
+    [
+      decorators.cyan("👤 Added Genesis Authority"),
+      decorators.green(node.name),
+      decorators.magenta(sr_account.address),
+    ],
+  ]);
+
+  new CreateLogTable({
+    colWidths: [120],
+  }).pushToPrint(chainSpec.genesis.runtime.authorMapping);
```
Comment (pepoviola) [inline javascript/packages/orchestrator/src/paras-decorators/moonbeam.ts:67]:
```suggestion
  }).pushToPrint([chainSpec.genesis.runtime.authorMapping]);
```
The ci is failing, I think this is the cause.

Thanks!

**Comment by pepoviola** [comment]
Fixes https://github.com/Moonsong-Labs/moonwall/issues/44
