### PR TITLE
Fix resources bug

### LINKED ISSUE #906: [Breaking] Error generating config from resources
### Issue Description

Whenever one tries to run podman the following errors appear and podman cannot run:

Error:  	 Error: Error generating config for prometheus resource
Error:  	 Error: Error generating config for tempo resource

### Steps to reproduce the issue

Steps to reproduce the issue
1. Execute any `spawn` with podman from `main` branch
2.
3.

### Describe the results you received

```
╔════════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════╗
║ 🧟 Zombienet 🧟    │ Initiation                                                                                         ║
╟────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ Provider           │ podman                                                                                             ║
╟────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ Namespace          │ zombie-c684f207                                                                                    ║
╟────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ Temp Dir           │ /tmp/zombie-c684f207_-74154-sx2pEcqiRJ8m                                                           ║
╚════════════════════╧════════════════════════════════════════════════════════════════════════════════════════════════════╝
!!!! templateConfigPath -> /home/wirednkod/Documents/repos/parity/ts/zombienet/javascript/configs/prometheus.yml
!!!! configPath -> /tmp/zombie-c684f207_-74154-sx2pEcqiRJ8m/prometeus/etc/prometheus.yml

	 Monitor: prometheus - url: http://127.0.0.1:46511
Error:  	 Error: Error generating config for tempo resource

undefined
┌────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Node'              │ /tmp/zombie-c684f207_-74154-sx2pEcqiRJ8m/logs                                                      │
│ s logs:            │                                                                                                    │
│ m                  │                                                                                                    │
└────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────┘

```

### Describe the results you expected

To run	

### Zombienet version

main branch

### Provider

Podman

### Provider version

```yaml
podman version 3.4.2
```

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by wirednkod**
Fixes #906

### CODE REVIEW

**Review by pepoviola — APPROVED** [review]

File: javascript/packages/orchestrator/src/providers/podman/resources/grafanaResource.ts [hunk 1]
```diff
@@ -56,8 +56,11 @@ export class GrafanaResource {
         `${this.dataSourcesPath}/prometheus.yml`,
         grafanaConfig,
       );
-    } catch {
-      throw new Error("Error generating config for grafana resource");
```
Comment (pepoviola) [inline javascript/packages/orchestrator/src/providers/podman/resources/grafanaResource.ts:60]: We shouldn't use this pattern, since the error message don't add any extra value about the err.
