### PR TITLE
always print logs

### LINKED ISSUE #665: Print loki URLs on successful run too
The links to loki were previously printed always if I remember correctly.
Recently they seem to be only available for failed runs.

This is a bit inconvenient, because it can be super useful to verify successful logs too:
- Check successful logs against failing ones
- Verify a successful test did what you think it did

To do this I currently need to manually query loki via the identifier printed.

### PR DESCRIPTION
**Pull request by pepoviola**
fix #665 
- Print always path/command for logs.

### CODE REVIEW

File: javascript/packages/orchestrator/src/test-runner/index.ts [hunk 1]
```diff
@@ -125,83 +125,99 @@ export async function run(
...
               await network.stop();
               break;
             case "kubernetes":
               if (inCI) {
-                // show links to grafana and also we need to move the logs to artifacts
-                const networkEndtime = new Date().getTime();
-                for (const node of network.relay) {
+                // keep pods running for 30 mins.
+                console.log(
+                  `\n\t${decorators.yellow(
```
Comment (wirednkod) [inline javascript/packages/orchestrator/src/test-runner/index.ts:150]: Lets do that .red since its a failure

**Review by wirednkod — APPROVED** [review]
Other than a nip tuck and the ci failing it looks good to me
