### PR TITLE
fix(orchestrator): Apply the x-infra-instance to fileserver pod

### LINKED ISSUE #1513: fileserver pod has no label for scheduling
After the label we agreed to take decision to schedule them on which nodes, it is turned out that fileserver pod doesn't have that label that I would be much appreciated if we can handle that also please.

### PR DESCRIPTION
**Pull request by pepoviola**
- Fix fileserver label for x-infra.
fix #1513

### CODE REVIEW

File: javascript/packages/orchestrator/src/providers/k8s/kubeClient.ts [hunk 1]
```diff
@@ -543,10 +543,7 @@ export class KubeClient extends Client {
       },
       {
         type: "deployment",
-        files: [
-          settings.backchannel ? "backchannel-pod.yaml" : null,
-          "fileserver-pod.yaml",
-        ],
+        files: [settings.backchannel ? "backchannel-pod.yaml" : null],
```
Comment (wirednkod) [inline javascript/packages/orchestrator/src/providers/k8s/kubeClient.ts:546]:
```suggestion
        files: settings.backchannel ? ["backchannel-pod.yaml"] : [],
```

**Review by wirednkod — APPROVED** [review]
Some nip tuck

File: javascript/packages/orchestrator/src/providers/k8s/kubeClient.ts (hunk 1 above)
Comment (pepoviola) [reply javascript/packages/orchestrator/src/providers/k8s/kubeClient.ts:546]: Thanks, I didn't saw this before merge. Can you add it in a follow up pr?
Thx!
